apiVersion: cosmosdb.azure.upbound.io/v1beta1
kind: Account
metadata:
  name: homelab-cosmos
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  forProvider:
    resourceGroupName: rg-ephemeral-demo
    location: westeurope
    offerType: Standard
    kind: GlobalDocumentDB
    enableFreeTier: true
    consistencyPolicy:
      - consistencyLevel: Session
    geoLocation:
      - location: westeurope
        failoverPriority: 0
    capabilities:
      - name: EnableServerless
  writeConnectionSecretToRef:
    name: homelab-cosmos-conn
    namespace: crossplane-system
  providerConfigRef:
    name: default-azure
