apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cosmos-conn-preview-sync
spec:
  namespaceSelector:
    matchLabels:
      preview: "true"
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1m
    secretStoreRef:
      name: k8s-cosmos-conn
      kind: ClusterSecretStore
    target:
      name: homelab-cosmos-conn
      creationPolicy: Owner
    data:
    - secretKey: attribute.primary_sql_connection_string
      remoteRef:
        key: homelab-cosmos-conn
        property: attribute.primary_sql_connection_string
