apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rgunasekaran-github/homelab-gitops.git
    targetRevision: feat/add-opa-policies
    path: gatekeeper

  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true