apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane-azure-provider
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    azure.workload.identity/client-id: "427c3ed0-ae45-4465-81a7-e3cd89e49093"
